### ISSUE TITLE
do a bool state to check if the resource is cached or not

### ISSUE THREAD

**Issue by Yarukon** [KillStr3aK/ResourcePrecacher#4]
cuz if the map have chicken in it, the resource will cache again (depending on how many chickens in the map), so it needs a boolean state to check if its cached or not, and use EventShutdown to set it back to false when changing map

**Comment by Yarukon** [comment]
```C#
public void OnPrecacheDetour(IntPtr a1, IntPtr context)
{
    if (!cached)
    {
        foreach (string resource in resourcesList)
        {
            this.Logger.LogInformation($"Caching resource {resource} ...");
            PrecacheResource(resource, context);
        }

        cached = true;
    }


    OnPrecacheHook.Original(a1, context);
}

[GameEventHandler]
public HookResult OnShutdown(EventServerShutdown @event, GameEventInfo info)
{
    cached = false;
    return HookResult.Continue;
}
```
like this

**Comment by KillStr3aK** [comment]
I'll consider your suggestion

**Comment by KillStr3aK** [comment]
is this a hypothesis or did you find anything related to this? I can't really recall if I had any issues with the plugin in general, regardless of chickens

**Comment by Yarukon** [comment]
> is this a hypothesis or did you find anything related to this? I can't really recall if I had any issues with the plugin in general, regardless of chickens

the game will call the Chicken::OnPrecache again if there's chicken entity in the map (call times depending on how many chickens in the map)

**Comment by KillStr3aK** [comment]
> > is this a hypothesis or did you find anything related to this? I can't really recall if I had any issues with the plugin in general, regardless of chickens
> 
> the game will call the Chicken::OnPrecache again if there's chicken entity in the map (call times depending on how many chickens in the map)

Are you sure? I have been testing it earlier and my hypothesis is: the amount of chickens on the map was never ever related to the function as the model is loaded by the game regardless of the amount of chickens, the function also got called on a random workshop map that had no chickens at all
