### ISSUE TITLE
server crash for windows

### ISSUE THREAD

**Issue by Shana0606** [KillStr3aK/ResourcePrecacher#5]
Hello
When this log is generated, the server freezes for 2 seconds and then crashes.
Only windows problem?

I'm using Resource Precacher v1.0.4
Metamod:Source version 2.0.0-dev+1258
CounterStrikeSharp Version: 141
OS: Windows 11
<img width="422" alt="server crash" src="https://github.com/KillStr3aK/ResourcePrecacher/assets/156150908/261b6d72-0fef-41a7-87d4-5731bf8207a5">

**Comment by KillStr3aK** [comment]
There were mentions about issues on windows earlier, would like to do some tests but I have no windows environment setup

**Comment by Shana0606** [comment]
oh...
Please let me know if there is anything I can do to help in a windows environment.
but I don't know if I can be of any help...

**Comment by metacop** [comment]
I have the same problem. It takes me the windows path of the model. I even changed the vmdl and vmdl_c extension and neither works. I only put two resources and the command console crashes and closes.

![image](https://github.com/KillStr3aK/ResourcePrecacher/assets/56640826/d2fcc9a3-5f34-48a9-9e1b-1f360b36022a)

**Comment by metacop** [comment]
after running it several times. I got this. but only sometimes this error appears. but the end is the same, it closes and does not start
![image](https://github.com/KillStr3aK/ResourcePrecacher/assets/56640826/8678f19c-6d9c-42d4-be1d-d2c600ad7718)

**Comment by metacop** [comment]
> There were mentions about issues on windows earlier, would like to do some tests but I have no windows environment setup

Leave some photos below, I have the same problem with Windows.

**Comment by metacop** [comment]
update: mount the server on linux and it works. It practically doesn't work on Windows.

**Comment by KillStr3aK** [comment]
I've been making progress towards this but windows is still unstable, will push an update related to it once I've figured out the issue

**Comment by metacop** [comment]
> I've been making progress towards this but windows is still unstable, will push an update related to it once I've figured out the issue

Thank you very much, we are attentive to the update as long as I continue working on Linux

**Comment by KillStr3aK** [comment]
this plugin will be obsolete once https://github.com/roflmuffin/CounterStrikeSharp/pull/358 is merged, so I close this issue
