### ISSUE TITLE
Models not loading 

### ISSUE THREAD

**Issue by BorislavKolev1994** [KillStr3aK/ResourcePrecacher#6]
Hi, am I the only one who is following each step, and after when I set some of the 6 default models set it default from the script creator and i become a big error , and the model is not loading somehow .... ?

**Comment by KillStr3aK** [comment]
You should wait for the update to change the core function to the builtin one

also maybe you set the paths in the wrong way, maybe show your config and code

**Comment by KillStr3aK** [comment]
Try the latest version and reopen the issue if the issue persists.

**Comment by BorislavKolev1994** [comment]
But wait , im speaking for this script https://github.com/DEAFPS/SharpTimerModelSetter/ , somehow i cannot post the issue there , and also the last update was 2/4 weeks ago , so no update...
