### ISSUE TITLE
https://github.com/DEAFPS/SharpTimerModelSetter/ Models not loading

### ISSUE THREAD

**Issue by BorislavKolev1994** [KillStr3aK/ResourcePrecacher#7]
Hi again , am I the only one who is following each step, when I set some of the 6 default models it default from the script creator and i become a big error , and the model is not loading somehow ..

**Comment by KillStr3aK** [comment]
As I said, without context there is nothing much I could say, maybe share your configuration file or something, also open issue on the given fork as they are not related to eachother anymore
